title: Versatile
description: A lightweight dependency injection framework for Python

# Use default GitHub Pages theme
theme: minima

# GitHub repository info
github:
  repository_url: https://github.com/poetix/versatile

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
baseurl: "/versatile"
url: "https://poetix.github.io"